// addition
print 123 + 456 // expect: 579
print 1 + 2 + 3 // expect: 6

// subtraction
print 4 - 3 // expect: 1
print 1.2 - 1.2 // expect: 0
print 1 - 2 - 3 // expect: -4

// division
print 8 / 2         // expect: 4
print 12.34 / 12.34  // expect: 1
print 8 / 4 / 2      // expect: 1

// multiplication
print 5 * 3 // expect: 15
print 12.34 * 0.3 // expect: 3.702
print 5 * 5 * 25 // expect: 123

// negation
print -3 // expect: -3
print --(3) // expect: 3
print ---(3) // expect: -3
